
package currency.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CurrencyService", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", wsdlLocation = "http://www.restfulwebservices.net/wcf/CurrencyService.svc?wsdl")
public class CurrencyService
    extends Service
{

    private final static URL CURRENCYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(currency.soapclient.CurrencyService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = currency.soapclient.CurrencyService.class.getResource(".");
            url = new URL(baseUrl, "http://www.restfulwebservices.net/wcf/CurrencyService.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.restfulwebservices.net/wcf/CurrencyService.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CURRENCYSERVICE_WSDL_LOCATION = url;
    }

    public CurrencyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurrencyService() {
        super(CURRENCYSERVICE_WSDL_LOCATION, new QName("http://www.restfulwebservices.net/ServiceContracts/2008/01", "CurrencyService"));
    }

    /**
     * 
     * @return
     *     returns ICurrencyService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICurrencyService")
    public ICurrencyService getBasicHttpBindingICurrencyService() {
        return super.getPort(new QName("http://www.restfulwebservices.net/ServiceContracts/2008/01", "BasicHttpBinding_ICurrencyService"), ICurrencyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICurrencyService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICurrencyService")
    public ICurrencyService getBasicHttpBindingICurrencyService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.restfulwebservices.net/ServiceContracts/2008/01", "BasicHttpBinding_ICurrencyService"), ICurrencyService.class, features);
    }

}
