
package currency.soapclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "DefaultFaultContract", targetNamespace = "http://GOTLServices.FaultContracts/2008/01")
public class ICurrencyServiceGetConversionRateDefaultFaultContractFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DefaultFaultContract faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ICurrencyServiceGetConversionRateDefaultFaultContractFaultFaultMessage(String message, DefaultFaultContract faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ICurrencyServiceGetConversionRateDefaultFaultContractFaultFaultMessage(String message, DefaultFaultContract faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: currency.soapclient.DefaultFaultContract
     */
    public DefaultFaultContract getFaultInfo() {
        return faultInfo;
    }

}
