
package currency.soapclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICurrencyService", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICurrencyService {


    /**
     * 
     * @param fromCurrency
     * @param toCurrency
     * @return
     *     returns currency.soapclient.Currency
     * @throws ICurrencyServiceGetConversionRateDefaultFaultContractFaultFaultMessage
     */
    @WebMethod(operationName = "GetConversionRate", action = "GetConversionRate")
    @WebResult(name = "GetConversionRateResult", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
    @RequestWrapper(localName = "GetConversionRate", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", className = "currency.soapclient.GetConversionRate")
    @ResponseWrapper(localName = "GetConversionRateResponse", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", className = "currency.soapclient.GetConversionRateResponse")
    public Currency getConversionRate(
        @WebParam(name = "FromCurrency", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
        CurrencyCode fromCurrency,
        @WebParam(name = "ToCurrency", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
        CurrencyCode toCurrency)
        throws ICurrencyServiceGetConversionRateDefaultFaultContractFaultFaultMessage
    ;

}
